version: "3.9"

services:

  acelerometro:
    build: ./svc-acel
    container_name: acelerometro
    privileged: true
    devices:
      - "/dev/mem:/dev/mem"
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/gpiochip0:/dev/gpiochip0"
      - "/dev/gpiochip1:/dev/gpiochip1"
      - "/dev/spidev0.0:/dev/spidev0.0"
      - "/dev/spidev0.1:/dev/spidev0.1"
    volumes:
      - ./data:/app/data
      - /proc/device-tree:/proc/device-tree:ro
      - /sys:/sys:ro
    environment:
      - PYTHONUNBUFFERED=1

  api:
    build: ./svc-api
    container_name: api
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1